### PR TITLE
coca-cola-can added

### PR DESCRIPTION
**Pull request by Obijuan**

### CODE REVIEW

**Comment by MrFreez** [comment]
Why did you need this model ? For a project ?

**Comment by PrzemoF** [comment]
Can we rename it to a soft-drink-can? Easier to find and copyright free name.

**Comment by Obijuan** [comment]
PrzemoF: yes, you are right. We should rename it

**Comment by Obijuan** [comment]
MrFeez: I find it useful for having a reference for the size of other designs. For example, If I place the can near a robot you inmediatle get a intuition of the size of the robot. You know if this is a big or small robot.

**Comment by MrFreez** [comment]
Smart !

**Pull request merged**
